# -*- coding: utf-8 -*-
"""Skolemization_example.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tGMqC3a8O-NGsGdGiDpzt33ZZLA9yMCZ
"""

# ================================================================
# Educational First-Order Logic Resolution Solver
# ================================================================

from dataclasses import dataclass
from typing import Tuple
import itertools
import random
import re


# ================================================================
# SETTINGS
# ================================================================

STRATEGY = "shortest"       # "shortest" or "random"
MAX_RESOLUTION_STEPS = 150
SHOW_FULL_KB_EACH_STEP = True

FOCUS_ON_C = True
FALLBACK_TO_GENERAL = True


# ================================================================
# INTERNAL / VISIBLE VARIABLE NAMES
# ================================================================

def visible_variable_name(name):
    """
    Hide internal standardized variable names.

    Examples:

        __v230_x -> x
        __v17_y  -> y
        __v3_z   -> z

    Ordinary variable names remain unchanged.
    """

    match = re.match(
        r"^__v\d+_(.+)$",
        name
    )

    if match:
        return match.group(1)

    return name


# ================================================================
# TERMS
# ================================================================

@dataclass(frozen=True)
class Term:
    name: str
    args: Tuple["Term", ...] = ()
    is_var: bool = False

    def __str__(self):

        shown_name = (
            visible_variable_name(self.name)
            if self.is_var
            else self.name
        )

        if self.args:

            return (
                f"{shown_name}("
                + ", ".join(
                    str(arg)
                    for arg in self.args
                )
                + ")"
            )

        return shown_name


# ================================================================
# FORMULAS
# ================================================================

@dataclass(frozen=True)
class Atom:
    pred: str
    args: Tuple[Term, ...]


@dataclass(frozen=True)
class Not:
    x: object


@dataclass(frozen=True)
class And:
    a: object
    b: object


@dataclass(frozen=True)
class Or:
    a: object
    b: object


@dataclass(frozen=True)
class Implies:
    a: object
    b: object


@dataclass(frozen=True)
class ForAll:
    var: str
    body: object


@dataclass(frozen=True)
class Exists:
    var: str
    body: object


@dataclass(frozen=True)
class Literal:
    atom: Atom
    negated: bool = False

    def __str__(self):

        prefix = (
            "¬"
            if self.negated
            else ""
        )

        return (
            prefix
            + atom_str(self.atom)
        )


# ================================================================
# DISPLAY
# ================================================================

def atom_str(atom):

    return (
        f"{atom.pred}("
        + ", ".join(
            str(arg)
            for arg in atom.args
        )
        + ")"
    )


def formula_str(f):

    if isinstance(f, Atom):
        return atom_str(f)

    if isinstance(f, Not):
        return "¬" + formula_str(f.x)

    if isinstance(f, And):
        return (
            f"({formula_str(f.a)} ∧ "
            f"{formula_str(f.b)})"
        )

    if isinstance(f, Or):
        return (
            f"({formula_str(f.a)} ∨ "
            f"{formula_str(f.b)})"
        )

    if isinstance(f, Implies):
        return (
            f"({formula_str(f.a)} → "
            f"{formula_str(f.b)})"
        )

    if isinstance(f, ForAll):
        return (
            f"∀{f.var} "
            f"{formula_str(f.body)}"
        )

    if isinstance(f, Exists):
        return (
            f"∃{f.var} "
            f"{formula_str(f.body)}"
        )

    raise TypeError(f)


def clause_str(clause):

    if len(clause) == 0:
        return "□"

    return " ∨ ".join(
        str(literal)
        for literal in clause
    )


def show_kb(
    kb,
    title="KB"
):

    print(
        "\n"
        + "-" * 70
    )

    print(title)

    print(
        "-" * 70
    )

    for i, clause in enumerate(
        kb,
        1
    ):

        print(
            f"C{i}: "
            f"{clause_str(clause)}"
        )

    print(
        "-" * 70
    )


# ================================================================
# PARSER
# ================================================================

TOKEN_RE = re.compile(
    r"\s*(->|-->|∀|∃|¬|!|\?|~|\(|\)|,|:|&|\||"
    r"[A-Za-z_][A-Za-z0-9_]*)"
)


def tokenize(text):

    result = []

    for token in TOKEN_RE.findall(
        text
    ):

        low = token.lower()

        if low in (
            "all",
            "forall"
        ):
            result.append(
                "forall"
            )

        elif low == "exists":
            result.append(
                "exists"
            )

        elif low == "not":
            result.append(
                "not"
            )

        elif low == "and":
            result.append(
                "and"
            )

        elif low == "or":
            result.append(
                "or"
            )

        elif token in (
            "->",
            "-->"
        ):
            result.append(
                "->"
            )

        elif token in (
            "¬",
            "~"
        ):
            result.append(
                "not"
            )

        elif token in (
            "∀",
            "!"
        ):
            result.append(
                "forall"
            )

        elif token in (
            "∃",
            "?"
        ):
            result.append(
                "exists"
            )

        elif token == "&":
            result.append(
                "and"
            )

        elif token == "|":
            result.append(
                "or"
            )

        else:
            result.append(
                token
            )

    return result


class Parser:

    def __init__(
        self,
        text
    ):

        self.tokens = tokenize(
            text
        )

        self.i = 0

        self.bound_variables = []

    def peek(self):

        if self.i >= len(
            self.tokens
        ):
            return None

        return self.tokens[
            self.i
        ]

    def eat(
        self,
        expected=None
    ):

        token = self.peek()

        if token is None:

            raise SyntaxError(
                "Unexpected end of formula"
            )

        if (
            expected is not None
            and token != expected
        ):

            raise SyntaxError(
                f"Expected '{expected}', "
                f"found '{token}'"
            )

        self.i += 1

        return token

    def parse(self):

        result = (
            self.parse_implication()
        )

        if self.peek() is not None:

            raise SyntaxError(
                f"Unexpected token: "
                f"{self.peek()}"
            )

        return result

    def parse_implication(self):

        left = self.parse_or()

        if self.peek() == "->":

            self.eat(
                "->"
            )

            right = (
                self.parse_implication()
            )

            return Implies(
                left,
                right
            )

        return left

    def parse_or(self):

        left = self.parse_and()

        while self.peek() == "or":

            self.eat(
                "or"
            )

            left = Or(
                left,
                self.parse_and()
            )

        return left

    def parse_and(self):

        left = self.parse_unary()

        while self.peek() == "and":

            self.eat(
                "and"
            )

            left = And(
                left,
                self.parse_unary()
            )

        return left

    def parse_unary(self):

        token = self.peek()

        if token == "not":

            self.eat(
                "not"
            )

            return Not(
                self.parse_unary()
            )

        if token in (
            "forall",
            "exists"
        ):

            quantifier = (
                self.eat()
            )

            variable = (
                self.eat()
            )

            if self.peek() in (
                ",",
                ":"
            ):
                self.eat()

            old_bound = list(
                self.bound_variables
            )

            self.bound_variables.append(
                variable
            )

            body = (
                self.parse_implication()
            )

            self.bound_variables = (
                old_bound
            )

            if (
                quantifier
                ==
                "forall"
            ):

                return ForAll(
                    variable,
                    body
                )

            return Exists(
                variable,
                body
            )

        if token == "(":

            self.eat(
                "("
            )

            result = (
                self.parse_implication()
            )

            self.eat(
                ")"
            )

            return result

        return self.parse_atom()

    def parse_atom(self):

        predicate = self.eat()

        self.eat(
            "("
        )

        args = []

        if self.peek() != ")":

            while True:

                args.append(
                    self.parse_term()
                )

                if self.peek() == ",":

                    self.eat(
                        ","
                    )

                    continue

                break

        self.eat(
            ")"
        )

        return Atom(
            predicate,
            tuple(args)
        )

    def parse_term(self):

        name = self.eat()

        if self.peek() == "(":

            self.eat(
                "("
            )

            args = []

            if self.peek() != ")":

                while True:

                    args.append(
                        self.parse_term()
                    )

                    if self.peek() == ",":

                        self.eat(
                            ","
                        )

                        continue

                    break

            self.eat(
                ")"
            )

            return Term(
                name,
                tuple(args),
                False
            )

        return Term(
            name,
            (),
            name
            in
            self.bound_variables
        )


# ================================================================
# SUBSTITUTION
# ================================================================

def substitute_term(
    term,
    substitution
):

    if (
        term.is_var
        and
        term.name in substitution
    ):

        return substitute_term(
            substitution[
                term.name
            ],
            substitution
        )

    if term.args:

        return Term(
            term.name,
            tuple(
                substitute_term(
                    arg,
                    substitution
                )
                for arg
                in term.args
            ),
            False
        )

    return term


def substitute_formula(
    f,
    substitution
):

    if isinstance(
        f,
        Atom
    ):

        return Atom(
            f.pred,
            tuple(
                substitute_term(
                    arg,
                    substitution
                )
                for arg
                in f.args
            )
        )

    if isinstance(
        f,
        Not
    ):

        return Not(
            substitute_formula(
                f.x,
                substitution
            )
        )

    if isinstance(
        f,
        And
    ):

        return And(
            substitute_formula(
                f.a,
                substitution
            ),
            substitute_formula(
                f.b,
                substitution
            )
        )

    if isinstance(
        f,
        Or
    ):

        return Or(
            substitute_formula(
                f.a,
                substitution
            ),
            substitute_formula(
                f.b,
                substitution
            )
        )

    if isinstance(
        f,
        Implies
    ):

        return Implies(
            substitute_formula(
                f.a,
                substitution
            ),
            substitute_formula(
                f.b,
                substitution
            )
        )

    if isinstance(
        f,
        ForAll
    ):

        smaller_sub = {
            k: v
            for k, v
            in substitution.items()
            if k != f.var
        }

        return ForAll(
            f.var,
            substitute_formula(
                f.body,
                smaller_sub
            )
        )

    if isinstance(
        f,
        Exists
    ):

        smaller_sub = {
            k: v
            for k, v
            in substitution.items()
            if k != f.var
        }

        return Exists(
            f.var,
            substitute_formula(
                f.body,
                smaller_sub
            )
        )

    raise TypeError(f)


# ================================================================
# REMOVE IMPLICATIONS
# ================================================================

def remove_implications(f):

    if isinstance(
        f,
        Atom
    ):
        return f

    if isinstance(
        f,
        Not
    ):

        return Not(
            remove_implications(
                f.x
            )
        )

    if isinstance(
        f,
        And
    ):

        return And(
            remove_implications(
                f.a
            ),
            remove_implications(
                f.b
            )
        )

    if isinstance(
        f,
        Or
    ):

        return Or(
            remove_implications(
                f.a
            ),
            remove_implications(
                f.b
            )
        )

    if isinstance(
        f,
        Implies
    ):

        return Or(
            Not(
                remove_implications(
                    f.a
                )
            ),
            remove_implications(
                f.b
            )
        )

    if isinstance(
        f,
        ForAll
    ):

        return ForAll(
            f.var,
            remove_implications(
                f.body
            )
        )

    if isinstance(
        f,
        Exists
    ):

        return Exists(
            f.var,
            remove_implications(
                f.body
            )
        )

    raise TypeError(f)


# ================================================================
# NEGATION NORMAL FORM
# ================================================================

def to_nnf(
    f,
    negated=False
):

    if isinstance(
        f,
        Atom
    ):

        if negated:
            return Not(f)

        return f

    if isinstance(
        f,
        Not
    ):

        return to_nnf(
            f.x,
            not negated
        )

    if isinstance(
        f,
        And
    ):

        if negated:

            return Or(
                to_nnf(
                    f.a,
                    True
                ),
                to_nnf(
                    f.b,
                    True
                )
            )

        return And(
            to_nnf(
                f.a
            ),
            to_nnf(
                f.b
            )
        )

    if isinstance(
        f,
        Or
    ):

        if negated:

            return And(
                to_nnf(
                    f.a,
                    True
                ),
                to_nnf(
                    f.b,
                    True
                )
            )

        return Or(
            to_nnf(
                f.a
            ),
            to_nnf(
                f.b
            )
        )

    if isinstance(
        f,
        ForAll
    ):

        if negated:

            return Exists(
                f.var,
                to_nnf(
                    f.body,
                    True
                )
            )

        return ForAll(
            f.var,
            to_nnf(
                f.body
            )
        )

    if isinstance(
        f,
        Exists
    ):

        if negated:

            return ForAll(
                f.var,
                to_nnf(
                    f.body,
                    True
                )
            )

        return Exists(
            f.var,
            to_nnf(
                f.body
            )
        )

    raise TypeError(f)


# ================================================================
# SKOLEMIZATION
# ================================================================

class SkolemNames:

    def __init__(self):

        self.function_counter = 0
        self.constant_counter = 0

    def new_function(
        self,
        universal_variables
    ):

        self.function_counter += 1

        return Term(
            f"g{self.function_counter}",
            tuple(
                Term(
                    variable,
                    (),
                    True
                )
                for variable
                in universal_variables
            ),
            False
        )

    def new_constant(self):

        self.constant_counter += 1

        if self.constant_counter == 1:
            name = "c"

        else:
            name = (
                f"c{self.constant_counter}"
            )

        return Term(
            name,
            (),
            False
        )


def skolemize(
    f,
    names,
    universal_variables=(),
    explanations=None
):

    if explanations is None:
        explanations = []

    if isinstance(
        f,
        (Atom, Not)
    ):

        return f

    if isinstance(
        f,
        And
    ):

        return And(
            skolemize(
                f.a,
                names,
                universal_variables,
                explanations
            ),
            skolemize(
                f.b,
                names,
                universal_variables,
                explanations
            )
        )

    if isinstance(
        f,
        Or
    ):

        return Or(
            skolemize(
                f.a,
                names,
                universal_variables,
                explanations
            ),
            skolemize(
                f.b,
                names,
                universal_variables,
                explanations
            )
        )

    if isinstance(
        f,
        ForAll
    ):

        return ForAll(
            f.var,
            skolemize(
                f.body,
                names,
                universal_variables
                +
                (f.var,),
                explanations
            )
        )

    if isinstance(
        f,
        Exists
    ):

        if universal_variables:

            replacement = (
                names.new_function(
                    universal_variables
                )
            )

        else:

            replacement = (
                names.new_constant()
            )

        explanations.append(
            (
                f.var,
                replacement,
                universal_variables
            )
        )

        new_body = (
            substitute_formula(
                f.body,
                {
                    f.var:
                    replacement
                }
            )
        )

        return skolemize(
            new_body,
            names,
            universal_variables,
            explanations
        )

    raise TypeError(f)


# ================================================================
# REMOVE UNIVERSAL QUANTIFIERS
# ================================================================

def remove_forall(f):

    if isinstance(
        f,
        ForAll
    ):

        return remove_forall(
            f.body
        )

    if isinstance(
        f,
        And
    ):

        return And(
            remove_forall(
                f.a
            ),
            remove_forall(
                f.b
            )
        )

    if isinstance(
        f,
        Or
    ):

        return Or(
            remove_forall(
                f.a
            ),
            remove_forall(
                f.b
            )
        )

    return f


# ================================================================
# CNF
# ================================================================

def distribute_or(
    a,
    b
):

    if isinstance(
        a,
        And
    ):

        return And(
            distribute_or(
                a.a,
                b
            ),
            distribute_or(
                a.b,
                b
            )
        )

    if isinstance(
        b,
        And
    ):

        return And(
            distribute_or(
                a,
                b.a
            ),
            distribute_or(
                a,
                b.b
            )
        )

    return Or(
        a,
        b
    )


def to_cnf(f):

    if isinstance(
        f,
        And
    ):

        return And(
            to_cnf(
                f.a
            ),
            to_cnf(
                f.b
            )
        )

    if isinstance(
        f,
        Or
    ):

        return distribute_or(
            to_cnf(
                f.a
            ),
            to_cnf(
                f.b
            )
        )

    return f


# ================================================================
# EXTRACT CLAUSES
# ================================================================

def flatten_or(f):

    if isinstance(
        f,
        Or
    ):

        return (
            flatten_or(
                f.a
            )
            +
            flatten_or(
                f.b
            )
        )

    if isinstance(
        f,
        Atom
    ):

        return [
            Literal(
                f,
                False
            )
        ]

    if (
        isinstance(
            f,
            Not
        )
        and
        isinstance(
            f.x,
            Atom
        )
    ):

        return [
            Literal(
                f.x,
                True
            )
        ]

    raise ValueError(
        "Expected clause, got: "
        + formula_str(f)
    )


def extract_clauses(f):

    if isinstance(
        f,
        And
    ):

        return (
            extract_clauses(
                f.a
            )
            +
            extract_clauses(
                f.b
            )
        )

    return [
        flatten_or(
            f
        )
    ]


# ================================================================
# RELATION PROPERTIES
# ================================================================

def add_relation_axioms(
    assumptions,
    symmetric_relations=None,
    transitive_relations=None,
    reflexive_relations=None
):

    symmetric_relations = set(
        symmetric_relations
        or
        []
    )

    transitive_relations = set(
        transitive_relations
        or
        []
    )

    reflexive_relations = set(
        reflexive_relations
        or
        []
    )

    result = list(
        assumptions
    )

    generated = []

    # ------------------------------------------------------------
    # Symmetry:
    #
    # ∀x∀y (R(x,y) -> R(y,x))
    # ------------------------------------------------------------

    for relation in sorted(
        symmetric_relations
    ):

        axiom = (
            f"all x all y "
            f"({relation}(x,y) -> "
            f"{relation}(y,x))"
        )

        result.append(
            axiom
        )

        generated.append(
            (
                "symmetric",
                relation,
                axiom
            )
        )

    # ------------------------------------------------------------
    # Transitivity:
    #
    # ∀x∀y∀z
    # ((R(x,y) and R(y,z)) -> R(x,z))
    # ------------------------------------------------------------

    for relation in sorted(
        transitive_relations
    ):

        axiom = (
            f"all x all y all z "
            f"(({relation}(x,y) and "
            f"{relation}(y,z)) -> "
            f"{relation}(x,z))"
        )

        result.append(
            axiom
        )

        generated.append(
            (
                "transitive",
                relation,
                axiom
            )
        )

    # ------------------------------------------------------------
    # Reflexivity:
    #
    # ∀x R(x,x)
    # ------------------------------------------------------------

    for relation in sorted(
        reflexive_relations
    ):

        axiom = (
            f"all x "
            f"{relation}(x,x)"
        )

        result.append(
            axiom
        )

        generated.append(
            (
                "reflexive",
                relation,
                axiom
            )
        )

    return (
        result,
        generated
    )


# ================================================================
# UNIFICATION
# ================================================================

def occurs(
    variable,
    term,
    substitution
):

    term = (
        substitute_term(
            term,
            substitution
        )
    )

    if term.is_var:

        return (
            term.name
            ==
            variable
        )

    return any(
        occurs(
            variable,
            arg,
            substitution
        )
        for arg
        in term.args
    )


def unify_variable(
    variable,
    term,
    substitution
):

    if variable in substitution:

        return unify_terms(
            substitution[
                variable
            ],
            term,
            substitution
        )

    if (
        term.is_var
        and
        term.name in substitution
    ):

        return unify_terms(
            Term(
                variable,
                (),
                True
            ),
            substitution[
                term.name
            ],
            substitution
        )

    if (
        term.is_var
        and
        term.name == variable
    ):

        return substitution

    if occurs(
        variable,
        term,
        substitution
    ):

        return None

    result = dict(
        substitution
    )

    result[
        variable
    ] = term

    return result


def unify_terms(
    a,
    b,
    substitution=None
):

    if substitution is None:
        substitution = {}

    a = substitute_term(
        a,
        substitution
    )

    b = substitute_term(
        b,
        substitution
    )

    if a == b:
        return substitution

    if a.is_var:

        return unify_variable(
            a.name,
            b,
            substitution
        )

    if b.is_var:

        return unify_variable(
            b.name,
            a,
            substitution
        )

    if (
        a.name != b.name
        or
        len(a.args)
        !=
        len(b.args)
    ):

        return None

    for x, y in zip(
        a.args,
        b.args
    ):

        substitution = (
            unify_terms(
                x,
                y,
                substitution
            )
        )

        if substitution is None:
            return None

    return substitution


def unify_atoms(
    a,
    b
):

    if (
        a.pred != b.pred
        or
        len(a.args)
        !=
        len(b.args)
    ):

        return None

    substitution = {}

    for x, y in zip(
        a.args,
        b.args
    ):

        substitution = (
            unify_terms(
                x,
                y,
                substitution
            )
        )

        if substitution is None:
            return None

    return substitution


def apply_substitution_literal(
    literal,
    substitution
):

    return Literal(
        Atom(
            literal.atom.pred,
            tuple(
                substitute_term(
                    arg,
                    substitution
                )
                for arg
                in literal.atom.args
            )
        ),
        literal.negated
    )


# ================================================================
# STANDARDIZE VARIABLES APART
#
# Internal only.
#
# These ugly names are NEVER shown because Term.__str__()
# converts them back to x, y, z...
# ================================================================

_fresh_counter = itertools.count()


def standardize_clause(
    clause
):

    prefix = (
        f"__v"
        f"{next(_fresh_counter)}_"
    )

    mapping = {}

    def rename_term(term):

        if term.is_var:

            if term.name not in mapping:

                original_name = (
                    visible_variable_name(
                        term.name
                    )
                )

                mapping[
                    term.name
                ] = Term(
                    prefix
                    + original_name,
                    (),
                    True
                )

            return mapping[
                term.name
            ]

        return Term(
            term.name,
            tuple(
                rename_term(
                    arg
                )
                for arg
                in term.args
            ),
            False
        )

    result = []

    for literal in clause:

        result.append(
            Literal(
                Atom(
                    literal.atom.pred,
                    tuple(
                        rename_term(
                            arg
                        )
                        for arg
                        in literal.atom.args
                    )
                ),
                literal.negated
            )
        )

    return result


# ================================================================
# CLEAN VARIABLES AFTER RESOLUTION
# ================================================================

def clean_clause_variables(
    clause
):

    """
    Convert surviving internal variables to clean names:

        x, y, z, u, v, w, x7, ...

    This is for storing the new clause in the visible KB.
    """

    mapping = {}

    preferred = [
        "x",
        "y",
        "z",
        "u",
        "v",
        "w"
    ]

    counter = 0

    def clean_term(term):

        nonlocal counter

        if term.is_var:

            if term.name not in mapping:

                original = (
                    visible_variable_name(
                        term.name
                    )
                )

                # Prefer original name if available and unused.
                used_names = {
                    t.name
                    for t
                    in mapping.values()
                }

                if (
                    original not in used_names
                    and
                    not original.startswith("__")
                ):

                    new_name = original

                elif counter < len(
                    preferred
                ):

                    while (
                        counter
                        <
                        len(preferred)
                        and
                        preferred[counter]
                        in used_names
                    ):
                        counter += 1

                    if counter < len(
                        preferred
                    ):

                        new_name = (
                            preferred[
                                counter
                            ]
                        )

                        counter += 1

                    else:

                        new_name = (
                            f"x{counter + 1}"
                        )

                        counter += 1

                else:

                    new_name = (
                        f"x{counter + 1}"
                    )

                    counter += 1

                mapping[
                    term.name
                ] = Term(
                    new_name,
                    (),
                    True
                )

            return mapping[
                term.name
            ]

        return Term(
            term.name,
            tuple(
                clean_term(
                    arg
                )
                for arg
                in term.args
            ),
            False
        )

    result = []

    for literal in clause:

        result.append(
            Literal(
                Atom(
                    literal.atom.pred,
                    tuple(
                        clean_term(
                            arg
                        )
                        for arg
                        in literal.atom.args
                    )
                ),
                literal.negated
            )
        )

    return result


# ================================================================
# CANONICAL REPRESENTATION
# ================================================================

def canonical_clause(
    clause
):

    """
    Alpha-equivalent clauses should count as the same clause.

    Example:
        P(x) ∨ Q(y)
        P(u) ∨ Q(v)

    are treated as identical.
    """

    mapping = {}
    counter = 0

    def canonical_term(term):

        nonlocal counter

        if term.is_var:

            if term.name not in mapping:

                counter += 1

                mapping[
                    term.name
                ] = (
                    f"V{counter}"
                )

            return mapping[
                term.name
            ]

        if term.args:

            return (
                term.name
                + "("
                + ",".join(
                    canonical_term(
                        arg
                    )
                    for arg
                    in term.args
                )
                + ")"
            )

        return term.name

    ordered_literals = sorted(
        clause,
        key=lambda literal: (
            literal.negated,
            literal.atom.pred,
            str(literal)
        )
    )

    result = []

    for literal in ordered_literals:

        sign = (
            "~"
            if literal.negated
            else "+"
        )

        result.append(
            sign
            + literal.atom.pred
            + "("
            + ",".join(
                canonical_term(
                    arg
                )
                for arg
                in literal.atom.args
            )
            + ")"
        )

    return tuple(
        sorted(result)
    )


# ================================================================
# TAUTOLOGY
# ================================================================

def clause_is_tautology(
    clause
):

    for i, first in enumerate(
        clause
    ):

        for j, second in enumerate(
            clause
        ):

            if i == j:
                continue

            if (
                first.negated
                !=
                second.negated
                and
                first.atom
                ==
                second.atom
            ):

                return True

    return False


# ================================================================
# RESOLUTION BETWEEN TWO CLAUSES
# ================================================================

def resolve_two_clauses(
    clause1,
    clause2
):

    left = (
        standardize_clause(
            clause1
        )
    )

    right = (
        standardize_clause(
            clause2
        )
    )

    possibilities = []

    for i, lit1 in enumerate(
        left
    ):

        for j, lit2 in enumerate(
            right
        ):

            if (
                lit1.negated
                ==
                lit2.negated
            ):

                continue

            substitution = (
                unify_atoms(
                    lit1.atom,
                    lit2.atom
                )
            )

            if substitution is None:
                continue

            resolvent = []

            for k, literal in enumerate(
                left
            ):

                if k != i:

                    resolvent.append(
                        apply_substitution_literal(
                            literal,
                            substitution
                        )
                    )

            for k, literal in enumerate(
                right
            ):

                if k != j:

                    resolvent.append(
                        apply_substitution_literal(
                            literal,
                            substitution
                        )
                    )

            unique = []

            for literal in resolvent:

                if literal not in unique:

                    unique.append(
                        literal
                    )

            if clause_is_tautology(
                unique
            ):

                continue

            clean_resolvent = (
                clean_clause_variables(
                    unique
                )
            )

            possibilities.append(
                (
                    lit1,
                    lit2,
                    substitution,
                    clean_resolvent
                )
            )

    return possibilities


# ================================================================
# HUMAN-READABLE SUBSTITUTIONS
# ================================================================

def meaningful_substitutions(
    substitution
):

    """
    Internal:
        __v230_x := g1(__v231_y)

    Visible:
        x := g1(y)

    Pure variable-to-variable bookkeeping is not printed.
    """

    result = []
    seen = set()

    for variable, value in substitution.items():

        final_value = (
            substitute_term(
                value,
                substitution
            )
        )

        # Don't show internal variable -> variable mappings.
        if final_value.is_var:
            continue

        shown_variable = (
            visible_variable_name(
                variable
            )
        )

        shown_value = str(
            final_value
        )

        key = (
            shown_variable,
            shown_value
        )

        if key in seen:
            continue

        seen.add(
            key
        )

        result.append(
            (
                shown_variable,
                shown_value
            )
        )

    return result


# ================================================================
# LOCAL SUBSUMPTION
# ================================================================

def match_term(
    pattern,
    target,
    substitution
):

    if pattern.is_var:

        if pattern.name in substitution:

            if (
                substitution[
                    pattern.name
                ]
                ==
                target
            ):

                return substitution

            return None

        result = dict(
            substitution
        )

        result[
            pattern.name
        ] = target

        return result

    if target.is_var:
        return None

    if (
        pattern.name
        !=
        target.name
    ):

        return None

    if (
        len(pattern.args)
        !=
        len(target.args)
    ):

        return None

    current = dict(
        substitution
    )

    for p, t in zip(
        pattern.args,
        target.args
    ):

        current = match_term(
            p,
            t,
            current
        )

        if current is None:
            return None

    return current


def match_literal(
    pattern,
    target,
    substitution
):

    if (
        pattern.negated
        !=
        target.negated
    ):

        return None

    if (
        pattern.atom.pred
        !=
        target.atom.pred
    ):

        return None

    if (
        len(pattern.atom.args)
        !=
        len(target.atom.args)
    ):

        return None

    current = dict(
        substitution
    )

    for p, t in zip(
        pattern.atom.args,
        target.atom.args
    ):

        current = match_term(
            p,
            t,
            current
        )

        if current is None:
            return None

    return current


def clause_subsumes(
    smaller,
    larger
):

    if (
        len(smaller)
        >
        len(larger)
    ):

        return False

    smaller = (
        standardize_clause(
            smaller
        )
    )

    larger = (
        standardize_clause(
            larger
        )
    )

    def backtrack(
        index,
        substitution,
        used
    ):

        if index == len(
            smaller
        ):

            return True

        pattern = (
            smaller[
                index
            ]
        )

        for j, target in enumerate(
            larger
        ):

            if j in used:
                continue

            new_sub = (
                match_literal(
                    pattern,
                    target,
                    substitution
                )
            )

            if new_sub is None:
                continue

            if backtrack(
                index + 1,
                new_sub,
                used | {j}
            ):

                return True

        return False

    return backtrack(
        0,
        {},
        set()
    )


def remove_redundant_parents(
    kb,
    parent1_index,
    parent2_index,
    resolvent
):

    """
    Check ONLY the two parents that produced the resolvent.
    """

    parent_indices = [
        parent1_index,
        parent2_index
    ]

    redundant = []

    for index in parent_indices:

        if clause_subsumes(
            resolvent,
            kb[index]
        ):

            redundant.append(
                index
            )

    print(
        "\n"
        + "-" * 70
    )

    print(
        "בדיקה האם אחד משני ה-parents הפך למיותר"
    )

    print(
        "-" * 70
    )

    if not redundant:

        print(
            "\nאף אחד משני ה-parents "
            "לא הפך למיותר."
        )

        print(
            "לכן לא מוחקים דבר."
        )

        return kb

    for index in redundant:

        parent = (
            kb[index]
        )

        print(
            "\nה-resolvent החדש:"
        )

        print(
            f"    {clause_str(resolvent)}"
        )

        print(
            "\nחזק יותר מה-parent:"
        )

        print(
            f"    {clause_str(parent)}"
        )

        print(
            "\nכל מצב שמקיים את ה-resolvent "
            "ממילא מקיים גם את ה-parent."
        )

        print(
            "לכן ה-parent אינו מוסיף מידע נוסף."
        )

        print(
            "\nמוחקים מה-KB:"
        )

        print(
            f"    {clause_str(parent)}"
        )

    for index in sorted(
        redundant,
        reverse=True
    ):

        del kb[
            index
        ]

    return kb


# ================================================================
# FOCUS ON EXISTENTIAL WITNESS c
# ================================================================

def term_contains_c(term):

    if (
        not term.is_var
        and
        term.name == "c"
        and
        not term.args
    ):

        return True

    return any(
        term_contains_c(
            arg
        )
        for arg
        in term.args
    )


def kb_contains_c(kb):

    for clause in kb:

        for literal in clause:

            for arg in literal.atom.args:

                if term_contains_c(
                    arg
                ):

                    return True

    return False


def instantiate_variable_with_c(
    clause,
    variable_name="x"
):

    substitution = {
        variable_name:
        Term(
            "c",
            (),
            False
        )
    }

    return [
        apply_substitution_literal(
            literal,
            substitution
        )
        for literal
        in clause
    ]


def focus_kb_on_c(kb):

    print(
        "\n"
        + "=" * 70
    )

    print(
        "שלב מיקוד ב-witness c"
    )

    print(
        "=" * 70
    )

    print(
        "\nנמצא witness קיומי בשם c."
    )

    print(
        "ננסה תחילה את ההצבה:"
    )

    print(
        "\n    x := c"
    )

    result = []

    for i, clause in enumerate(
        kb,
        1
    ):

        new_clause = (
            instantiate_variable_with_c(
                clause,
                "x"
            )
        )

        print(
            f"\nC{i}:"
        )

        print(
            "לפני:",
            clause_str(
                clause
            )
        )

        print(
            "אחרי:",
            clause_str(
                new_clause
            )
        )

        result.append(
            new_clause
        )

    show_kb(
        result,
        "KB לאחר המיקוד ב-c"
    )

    return result


# ================================================================
# RESOLUTION SEARCH
# ================================================================

def run_resolution_search(
    starting_kb,
    title="Resolution"
):

    kb = [
        list(clause)
        for clause
        in starting_kb
    ]

    # Remember every clause ever produced,
    # even if later removed as redundant.
    ever_seen = {
        canonical_clause(
            clause
        )
        for clause
        in kb
    }

    print(
        "\n"
        + "=" * 70
    )

    print(title)

    print(
        "=" * 70
    )

    show_kb(
        kb,
        "KB בתחילת החיפוש"
    )

    for step in range(
        1,
        MAX_RESOLUTION_STEPS
        +
        1
    ):

        candidates = []

        # --------------------------------------------------------
        # Find all NEW possible resolutions
        # --------------------------------------------------------

        for i in range(
            len(kb)
        ):

            for j in range(
                i + 1,
                len(kb)
            ):

                possibilities = (
                    resolve_two_clauses(
                        kb[i],
                        kb[j]
                    )
                )

                for (
                    lit1,
                    lit2,
                    substitution,
                    resolvent
                ) in possibilities:

                    key = (
                        canonical_clause(
                            resolvent
                        )
                    )

                    if key in ever_seen:
                        continue

                    candidates.append(
                        (
                            i,
                            j,
                            lit1,
                            lit2,
                            substitution,
                            resolvent
                        )
                    )

        # --------------------------------------------------------
        # Saturation
        # --------------------------------------------------------

        if not candidates:

            print(
                "\n"
                + "#" * 70
            )

            print(
                "SATURATED_NO_CONTRADICTION"
            )

            print(
                "#" * 70
            )

            print(
                "\nאין resolvent חדש "
                "שאפשר להוסיף."
            )

            print(
                "לא נמצאה הפסוקית הריקה □."
            )

            return (
                "SATURATED_NO_CONTRADICTION",
                kb
            )

        # --------------------------------------------------------
        # Choose candidate
        # --------------------------------------------------------

        if (
            STRATEGY
            ==
            "random"
        ):

            chosen = (
                random.choice(
                    candidates
                )
            )

        else:

            chosen = min(
                candidates,
                key=lambda item: (
                    len(
                        item[5]
                    ),
                    len(
                        kb[
                            item[0]
                        ]
                    )
                    +
                    len(
                        kb[
                            item[1]
                        ]
                    )
                )
            )

        (
            i,
            j,
            lit1,
            lit2,
            substitution,
            resolvent
        ) = chosen

        parent1 = list(
            kb[i]
        )

        parent2 = list(
            kb[j]
        )

        # --------------------------------------------------------
        # Explain step
        # --------------------------------------------------------

        print(
            "\n"
            + "=" * 70
        )

        print(
            f"Resolution step {step}"
        )

        print(
            "=" * 70
        )

        print(
            "\nבוחרים:"
        )

        print(
            f"\nC{i+1}: "
            f"{clause_str(parent1)}"
        )

        print(
            f"C{j+1}: "
            f"{clause_str(parent2)}"
        )

        print(
            "\nהליטרלים שניתן להצליב:"
        )

        # Important:
        # Term.__str__ hides __vXXX_ names here.
        print(
            f"    {lit1}"
        )

        print(
            f"    {lit2}"
        )

        substitutions = (
            meaningful_substitutions(
                substitution
            )
        )

        print(
            "\nההצבה הדרושה:"
        )

        if substitutions:

            for (
                variable,
                value
            ) in substitutions:

                print(
                    f"    {variable} := {value}"
                )

        else:

            print(
                "    אין צורך בהצבה ממשית."
            )

        # Show instantiated literals
        instantiated1 = (
            apply_substitution_literal(
                lit1,
                substitution
            )
        )

        instantiated2 = (
            apply_substitution_literal(
                lit2,
                substitution
            )
        )

        print(
            "\nלאחר ההצבה:"
        )

        print(
            f"    {instantiated1}"
        )

        print(
            f"    {instantiated2}"
        )

        print(
            "\nהליטרלים זהים פרט לשלילה, "
            "ולכן מבטלים אותם."
        )

        print(
            "\nמתקבל:"
        )

        print(
            f"    {clause_str(resolvent)}"
        )

        ever_seen.add(
            canonical_clause(
                resolvent
            )
        )

        # --------------------------------------------------------
        # CONTRADICTION
        # --------------------------------------------------------

        if len(
            resolvent
        ) == 0:

            kb.append(
                resolvent
            )

            show_kb(
                kb,
                "KB הסופי"
            )

            print(
                "\n"
                + "#" * 70
            )

            print(
                "PROVED"
            )

            print(
                "#" * 70
            )

            print(
                "\nהתקבלה הפסוקית הריקה:"
            )

            print(
                "\n                  □"
            )

            print(
                "\nנמצאה סתירה."
            )

            print(
                "ההנחות יחד עם שלילת המסקנה "
                "אינן יכולות להיות אמיתיות יחד."
            )

            print(
                "\nלכן המסקנה נובעת מן ההנחות."
            )

            return (
                "PROVED",
                kb
            )

        # --------------------------------------------------------
        # Check ONLY current parents for redundancy
        # --------------------------------------------------------

        kb = (
            remove_redundant_parents(
                kb,
                i,
                j,
                resolvent
            )
        )

        # --------------------------------------------------------
        # Add resolvent
        # --------------------------------------------------------

        print(
            "\nמוסיפים את ה-resolvent ל-KB:"
        )

        print(
            f"    {clause_str(resolvent)}"
        )

        kb.append(
            resolvent
        )

        if (
            SHOW_FULL_KB_EACH_STEP
        ):

            show_kb(
                kb,
                "KB בסוף הצעד"
            )

    # ------------------------------------------------------------
    # Search limit
    # ------------------------------------------------------------

    print(
        "\n"
        + "#" * 70
    )

    print(
        "UNKNOWN"
    )

    print(
        "#" * 70
    )

    print(
        f"\nהגענו ל-"
        f"{MAX_RESOLUTION_STEPS} "
        "צעדי Resolution."
    )

    print(
        "לא נמצאה סתירה, "
        "אבל החיפוש עדיין לא מוצה."
    )

    return (
        "UNKNOWN",
        kb
    )


# ================================================================
# PREPROCESSING
# ================================================================

def preprocess(
    assumptions,
    conclusion
):

    parsed_assumptions = [
        Parser(
            text
        ).parse()
        for text
        in assumptions
    ]

    parsed_conclusion = (
        Parser(
            conclusion
        ).parse()
    )

    formulas = (
        parsed_assumptions
        +
        [
            Not(
                parsed_conclusion
            )
        ]
    )

    # ============================================================
    # 1. NEGATE CONCLUSION
    # ============================================================

    print(
        "\n"
        + "=" * 70
    )

    print(
        "1. שוללים את המסקנה ומוסיפים אותה ל-KB"
    )

    print(
        "=" * 70
    )

    for i, formula in enumerate(
        formulas,
        1
    ):

        print(
            f"F{i}: "
            f"{formula_str(formula)}"
        )

    # ============================================================
    # 2. REMOVE IMPLICATIONS
    # ============================================================

    print(
        "\n"
        + "=" * 70
    )

    print(
        "2. ביטול גרירות"
    )

    print(
        "=" * 70
    )

    print(
        "\nP → Q   הופך ל-   ¬P ∨ Q"
    )

    no_implications = []

    for i, formula in enumerate(
        formulas,
        1
    ):

        new_formula = (
            remove_implications(
                formula
            )
        )

        print(
            f"\nF{i}:"
        )

        print(
            "לפני:",
            formula_str(
                formula
            )
        )

        print(
            "אחרי:",
            formula_str(
                new_formula
            )
        )

        no_implications.append(
            new_formula
        )

    # ============================================================
    # 3. NNF
    # ============================================================

    print(
        "\n"
        + "=" * 70
    )

    print(
        "3. הכנסת השלילות פנימה"
    )

    print(
        "=" * 70
    )

    nnf = []

    for i, formula in enumerate(
        no_implications,
        1
    ):

        new_formula = (
            to_nnf(
                formula
            )
        )

        print(
            f"\nF{i}:"
        )

        print(
            "לפני:",
            formula_str(
                formula
            )
        )

        print(
            "אחרי:",
            formula_str(
                new_formula
            )
        )

        nnf.append(
            new_formula
        )

    # ============================================================
    # 4. SKOLEMIZATION
    # ============================================================

    print(
        "\n"
        + "=" * 70
    )

    print(
        "4. Skolemization"
    )

    print(
        "=" * 70
    )

    names = (
        SkolemNames()
    )

    skolemized = []

    for i, formula in enumerate(
        nnf,
        1
    ):

        explanations = []

        new_formula = (
            skolemize(
                formula,
                names,
                explanations=explanations
            )
        )

        print(
            f"\nF{i}:"
        )

        print(
            "לפני:",
            formula_str(
                formula
            )
        )

        if not explanations:

            print(
                "אין כמת קיומי לסלק."
            )

        for (
            variable,
            replacement,
            universals
        ) in explanations:

            if universals:

                print(
                    f"∃{variable} נמצא תחת "
                    +
                    ", ".join(
                        f"∀{u}"
                        for u
                        in universals
                    )
                )

                print(
                    "לכן הוא עשוי להיות תלוי בהם."
                )

                print(
                    "מציבים:"
                )

                print(
                    f"    {variable} := {replacement}"
                )

            else:

                print(
                    f"∃{variable} אינו תלוי "
                    "במשתנה אוניברסלי."
                )

                print(
                    "לכן בוחרים witness קבוע:"
                )

                print(
                    f"    {variable} := {replacement}"
                )

        print(
            "אחרי:",
            formula_str(
                new_formula
            )
        )

        skolemized.append(
            new_formula
        )

    # ============================================================
    # 5. REMOVE FORALL
    # ============================================================

    print(
        "\n"
        + "=" * 70
    )

    print(
        "5. הורדת כמתי ∀"
    )

    print(
        "=" * 70
    )

    without_forall = [
        remove_forall(
            formula
        )
        for formula
        in skolemized
    ]

    for i, formula in enumerate(
        without_forall,
        1
    ):

        print(
            f"F{i}: "
            f"{formula_str(formula)}"
        )

    # ============================================================
    # 6. CNF
    # ============================================================

    print(
        "\n"
        + "=" * 70
    )

    print(
        "6. מעבר ל-CNF"
    )

    print(
        "=" * 70
    )

    print(
        "\nP ∨ (Q ∧ R)"
        "  הופך ל-  "
        "(P ∨ Q) ∧ (P ∨ R)"
    )

    cnf = []

    for i, formula in enumerate(
        without_forall,
        1
    ):

        new_formula = (
            to_cnf(
                formula
            )
        )

        print(
            f"\nF{i}:"
        )

        print(
            "לפני:",
            formula_str(
                formula
            )
        )

        print(
            "אחרי:",
            formula_str(
                new_formula
            )
        )

        cnf.append(
            new_formula
        )

    # ============================================================
    # 7. CLAUSES
    # ============================================================

    clauses = []

    for formula in cnf:

        clauses.extend(
            extract_clauses(
                formula
            )
        )

    print(
        "\n"
        + "=" * 70
    )

    print(
        "7. ה-KB בצורת clauses"
    )

    print(
        "=" * 70
    )

    show_kb(
        clauses,
        "KB לפני Resolution"
    )

    return clauses


# ================================================================
# PUBLIC FUNCTION
# ================================================================

def prove(
    assumptions,
    conclusion,
    symmetric_relations=None,
    transitive_relations=None,
    reflexive_relations=None
):

    symmetric_relations = set(
        symmetric_relations
        or
        []
    )

    transitive_relations = set(
        transitive_relations
        or
        []
    )

    reflexive_relations = set(
        reflexive_relations
        or
        []
    )

    # ============================================================
    # ADD RELATION AXIOMS
    # ============================================================

    (
        extended_assumptions,
        generated_axioms
    ) = add_relation_axioms(
        assumptions,
        symmetric_relations,
        transitive_relations,
        reflexive_relations
    )

    print(
        "\n"
        + "=" * 70
    )

    print(
        "0. הוספת תכונות של יחסים ל-KB"
    )

    print(
        "=" * 70
    )

    if not generated_axioms:

        print(
            "\nלא הוגדרו תכונות מיוחדות של יחסים."
        )

    else:

        for (
            property_name,
            relation,
            axiom
        ) in generated_axioms:

            if (
                property_name
                ==
                "symmetric"
            ):

                description = (
                    "סימטרי"
                )

            elif (
                property_name
                ==
                "transitive"
            ):

                description = (
                    "טרנזיטיבי"
                )

            else:

                description = (
                    "רפלקסיבי"
                )

            print(
                f"\n{relation} הוגדר כיחס "
                f"{description}."
            )

            print(
                "מוסיפים ל-KB:"
            )

            print(
                f"    {axiom}"
            )

    print(
        "\nההנחות שאיתן נעבוד:"
    )

    for i, assumption in enumerate(
        extended_assumptions,
        1
    ):

        print(
            f"{i}. {assumption}"
        )

    print(
        "\nהמסקנה:"
    )

    print(
        conclusion
    )

    # ============================================================
    # PREPROCESS
    # ============================================================

    original_kb = (
        preprocess(
            extended_assumptions,
            conclusion
        )
    )

    # ============================================================
    # FOCUSED SEARCH
    # ============================================================

    if (
        FOCUS_ON_C
        and
        kb_contains_c(
            original_kb
        )
    ):

        focused_kb = (
            focus_kb_on_c(
                original_kb
            )
        )

        (
            status,
            final_kb
        ) = (
            run_resolution_search(
                focused_kb,
                "Resolution ממוקד ב-c"
            )
        )

        if (
            status
            ==
            "PROVED"
        ):

            print(
                "\n"
                + "=" * 70
            )

            print(
                "FINAL STATUS: PROVED"
            )

            print(
                "=" * 70
            )

            return (
                "PROVED"
            )

        if not FALLBACK_TO_GENERAL:

            print(
                "\nFINAL STATUS:",
                status
            )

            return status

        print(
            "\n"
            + "=" * 70
        )

        print(
            "החיפוש הממוקד הסתיים ללא הוכחה"
        )

        print(
            "=" * 70
        )

        print(
            "\nהמיקוד ב-c הוא heuristic בלבד."
        )

        print(
            "לכן חוזרים ל-KB המקורי "
            "ומנסים Resolution כללי."
        )

    # ============================================================
    # GENERAL SEARCH
    # ============================================================

    (
        status,
        final_kb
    ) = run_resolution_search(
        original_kb,
        "Resolution כללי"
    )

    print(
        "\n"
        + "=" * 70
    )

    print(
        "FINAL STATUS:",
        status
    )

    print(
        "=" * 70
    )

    return status

"""דוגמה:

הנחות:

1. כל כלב יש בעלים והוא נאמן לו

2. מי שנאמן למישהו לא בוגד בו

3. קיים מישהו שבוגד בכולם


מסקנה:

קיים מישהו שבוגד בכולם ואינו כלב



הצרנה:

הגדרות:

D(x): x is a dog

O(x,y): y is owner of x

F(x,y): x is loyal to y

B(x,y): x betrays on y



Assumptions:

1. all x, (D(x) -> exists y (O(x,y) and F(x,y))

2. all x all y (F(x,y) -> not B(x,y))

3. exists x, all y B(x,y)


Conclusion:

exists x ( (all y B(x,y)) and not D(x))

מסקנה שנובעת מההנחות:

קיים איקס שבוגד בכולם והוא לא כלב
"""

assumptions = [
    "all x, D(x) -> (exists y (O(x,y) and F(x,y)))",
    "all x all y (F(x,y) -> not B(x,y))",
    "exists x, all y B(x,y)"
]

conclusion = (
    "exists x, ((all y B(x,y)) and not D(x))"
)

result = prove(
    assumptions,
    conclusion
)

"""מסקנה ש **לא** נובעת מההנחות:

קיים כלב שבוגד בכולם
"""

# מסקנה שלא נובעת מההנחות
# קיים x שבוגד בכולם והוא כלב

assumptions = [
    "all x, D(x) -> (exists y (O(x,y) and F(x,y)))",
    "all x all y (F(x,y) -> not B(x,y))",
    "exists x, all y B(x,y)"
]

conclusion = (
    "exists x, ((all y B(x,y)) and D(x))"
)

result = prove(
    assumptions,
    conclusion
)

"""מסקנה ש **לא** נובעת מההנחות:

קיים כלב
"""

# מסקנה שלא נובעת מההנחות
# קיים כלב

assumptions = [
    "all x, D(x) -> (exists y (O(x,y) and F(x,y)))",
    "all x all y (F(x,y) -> not B(x,y))",
    "exists x, all y B(x,y)"
]

conclusion = (
    "exists x, D(x)"
)

result = prove(
    assumptions,
    conclusion
)

# מסקנה שלא נובעת מההנחות
# קיים איקס שנאמן לווי

assumptions = [
    "all x, D(x) -> (exists y (O(x,y) and F(x,y)))",
    "all x all y (F(x,y) -> not B(x,y))",
    "exists x, all y B(x,y)"
]

conclusion = (
    "exists x, exists y, F(x,y)"
)

result = prove(
    assumptions,
    conclusion
)

#  מסקנה שלא נובעת מההנחות כפי שנוסחו כאן
# אם y בעלים של x אז x לא בוגד ב y
# למה לא נובעת? כי רק טענו שלכל כלב יש בעלים ושהוא נאמן לו.
# למעשה אפשר היה לדלג על הבעלים, כתוב רק שהוא נאמן למישהו

assumptions = [
    "all x, D(x) -> (exists y (O(x,y) and F(x,y)))",
    "all x all y (F(x,y) -> not B(x,y))",
    "exists x, all y B(x,y)"
]

conclusion = (
    "all x, all y, O(x,y) -> not B(x,y)"
)

result = prove(
    assumptions,
    conclusion
)

# עאבל אם ננסח את ההנחות באופן שונה, זה כן ינבע
# לכל כלב יש בעלים
# אם y בעלים של x אז x נאמן ל y
# כל יתר ההנחות כמו קודם
assumptions = [
    "all x, D(x) -> (exists y O(x,y))",
    "all x all y (O(x,y) -> F(x,y))",
    "all x all y (F(x,y) -> not B(x,y))",
    "exists x, all y B(x,y)"
]

conclusion = (
    "all x, all y, O(x,y) -> not B(x,y)"
)

result = prove(
    assumptions,
    conclusion
)

"""שאלה 3 סעיף א

נתון ההיגד:

"(all x all y

((P(x) and P(y)) -> x=y)))

and

exists x P(x)"


והשאלה האם הוא גורר את המסקנה:

"exists x

(P(x)

and

(all y (P(y) -> y=x)))

במילים:

יש איזו פונקציה בוליאנית שמקיימת

p(x) and p(y) -> x=y

כלומר היא מקבלת ערך אמת רק על ערך מסוים, על כל היתר היא מקבלת ערך שקר


וגם ידוע שקיים x ש p מקבלת ערך אמת עליו

צריך להוכיח:

קיים x כך ש p מקבלת ערך אמת עליו

כך שלכל y

אם p(y)

אז y=x


כלומר

קיים x

כך ש p מקבלת עליו אמת

וגם

p מקיימת את התכונה הנ"ל ביחס אליו ספציפית

זה נובע מההנחות

---------


נשים לב שצריך להוסיף במפורש את העובדה שיחס שוויון הוא סימטרי


אחרת הוא לא ידע ש

x=y, y=x

 זה אותו דבר


הוספתי גם את המידע שיחס השוויון הוא טרזנטיבי ורפלקסיבי

(למרות שזה לא נדרש כאן)

for good measure

כשמגדירים לסולבר שיחס מסוים מקיים תכונה מסוימת, הוא מוסיף ל

Knowledge base

היגד מתאים

לדוגמה אם מגדירים לו שהיחס סימטרי,

הוא מוסיף את ההיגד:

all x all y (Eq(x,y) -> Eq(y,x))
"""

# שאלה 3 סעיף א
# נשים לב שצריך להוסיף במפורש את העובדה שילב שוויון הוא סימטרי (וגם טרזנטיבי ורפלקסיביחם for good measure)
assumptions = [
    "all x all y ((P(x) and P(y)) -> Eq(x,y))",
    "exists x P(x)"
]

conclusion = (
    "exists x "
    "(P(x) and "
    "(all y (P(y) -> Eq(y,x))))"
)


# ------------------------------------------------
# Properties of relations
# ------------------------------------------------

symmetric_relations = {
    "Eq"
}

transitive_relations = {
    "Eq"
}

reflexive_relations = {
    "Eq"
}


# ------------------------------------------------
# Run
# ------------------------------------------------

result = prove(
    assumptions,
    conclusion,
    symmetric_relations=symmetric_relations,
    transitive_relations=transitive_relations,
    reflexive_relations=reflexive_relations
)

"""לחילופין אפשר פשוט לכתוב לו את הנוסחה בצורה זהה בשני המקרים:

Eq(x,y)

במקרה הספציפי הזה זה יספיק

אבל במקרים מורכבים יותר, שהוא צריך להסיק באמצעות סימטריות, טרנזיטיביות וכו' - זה לא יעבוד
"""

assumptions = [
    "all x all y ((P(x) and P(y)) -> Eq(x,y))",
    "exists x P(x)"
]

conclusion = (
    "exists x "
    "(P(x) and "
    "(all y (P(y) -> Eq(x,y))))"
)


# ------------------------------------------------
# Run
# ------------------------------------------------

result = prove(
    assumptions,
    conclusion
)

"""שאלה 3

ננסה להוכיח/להפריך בשיטת הרברנד
המשמעות ששני פסוקים שקולים לוגית היא

phi1<-->phi2

כלומר

phi1 -> phi2

and

phi2 -> phi1

כלומר יש כאן "גם" של שתי (הנחות, מסקנה)

אם שתי הטענות נכונות אז הם שקולים לוגית

אם לפחות אחת מהם לא נכונה אז הם אינם שקולים לוגית
"""

phi1 = (
    "(all x (P(x) -> exists y Q(x,y))) "
    "-> exists x exists y Q(x,y)"
)

phi2 = (
    "(exists x (P(x) -> exists y Q(x,y))) "
    "-> exists x exists y Q(x,y)"
)


print("\n" + "=" * 80)
print("בדיקת כיוון 1:  φ1 ⊨ φ2")
print("=" * 80)

result_1 = prove(
    assumptions=[phi1],
    conclusion=phi2,
    symmetric_relations=set(),
    transitive_relations=set(),
    reflexive_relations=set()
)


print("\n\n" + "=" * 80)
print("בדיקת כיוון 2:  φ2 ⊨ φ1")
print("=" * 80)

result_2 = prove(
    assumptions=[phi2],
    conclusion=phi1,
    symmetric_relations=set(),
    transitive_relations=set(),
    reflexive_relations=set()
)


print("\n\n" + "=" * 80)
print("תוצאה סופית")
print("=" * 80)

if result_1 == "PROVED" and result_2 == "PROVED":
    print("✅ שתי הגרירות הוכחו.")
    print("לכן:")
    print("    φ1 ≡ φ2")

elif result_1 == "PROVED" and result_2 != "PROVED":
    print("הוכח:")
    print("    φ1 ⊨ φ2")
    print("אבל הכיוון:")
    print("    φ2 ⊨ φ1")
    print("לא הוכח.")

elif result_1 != "PROVED" and result_2 == "PROVED":
    print("הוכח:")
    print("    φ2 ⊨ φ1")
    print("אבל הכיוון:")
    print("    φ1 ⊨ φ2")
    print("לא הוכח.")

else:
    print("לא הוכחו שתי הגרירות.")
    print("לכן ה-solver לא הוכיח שקילות.")

"""שאלה 8"""

assumptions = [
    "all x ((Pr(x) and L(x)) -> C(x))",
    "all x (C(x) -> B(x))",
    "exists x (Pr(x) and not B(x))"
]

conclusion = (
    "exists x (Pr(x) and not L(x))"
)

result = prove(
    assumptions,
    conclusion
)

"""מה יקרה אם נשתמש בנוסחה כפי שהוגדרה בשאלה

פעם אחת

Eq(x,y) (x=y)

ופעם אחת

Eq(y,x) (y=x)

ולא נוסיף לו את הנתון שהיחס סימטרי?

אז מאחר והוא לא יודע ששני הדברים שקולים, הוא לא ימצא סתירה
"""

input("\n" + "=" * 80)
# מה יקרה אם לא נוסיף, ומשתמש הנוסחה כפי שהוגדרה בשאלה x=y, y=x?
assumptions = [
    "all x all y ((P(x) and P(y)) -> Eq(x,y))",
    "exists x P(x)"
]

conclusion = (
    "exists x "
    "(P(x) and "
    "(all y (P(y) -> Eq(y,x))))"
)


# ------------------------------------------------
# Run
# ------------------------------------------------

result = prove(
    assumptions,
    conclusion
)